- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
    - id: autopep8
      args: ['--max-line-length=79']

- repo: https://github.com/pre-commit/mirrors-black
  rev: v23.1.0
  hooks:
    - id: black
      args: ['--line-length=79']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.11.4
  hooks:
    - id: isort
      args: ['--profile', 'black']
